# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-02 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Amount_To_Pay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=100)),
                ('Opening_Balance', models.IntegerField()),
                ('Receipt', models.IntegerField()),
                ('Total', models.PositiveIntegerField(default=0, editable=False)),
                ('Sale', models.IntegerField()),
                ('Closing_Balance', models.IntegerField(default=0, editable=False)),
                ('Invoice_Number', models.CharField(max_length=13)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilizers.Company')),
            ],
        ),
    ]
