# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Amount_To_Pay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Seller_name', models.CharField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=13)),
                ('Purchase_Date', models.DateField(default=datetime.datetime(2018, 4, 9, 17, 23, 24, 259546, tzinfo=utc), verbose_name='Date')),
                ('Count', models.IntegerField()),
                ('Price_Per_Piece', models.FloatField()),
                ('Total_Amount', models.PositiveIntegerField(default=0, editable=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilizers.Company')),
            ],
        ),
    ]
